"""
FotMob Match Report Generator
==============================

Scrapes a FotMob match page and builds an Excel workbook with:
  - Shots: one row per shot (the "shot map") - player, minute, situation,
    body part, outcome, xG, xGOT, and pitch coordinates as FotMob reports
    them.
  - Shot Breakdown: the Shots tab rolled up per team along three
    dimensions - by player, by situation (open play/set piece/penalty/
    corner/fast break), and by body part.
  - Totals: team-level numbers rolled up from the shot map (Shots, Shots
    on Target, Goals, Total xG) plus whatever aggregated match stats
    FotMob itself publishes for the match (possession, corners, fouls,
    cards, passes, etc. - whichever stat groups FotMob includes for a
    given match). A second table below it splits xG by half and by
    phase (Open Play vs Set Piece).
  - Plus Minus: one table per team, one row per player, showing Goals
    For/Against, Shots For/Against, and xG For/Against for exactly the
    minutes that player was on the pitch (from FotMob's own lineup/
    substitution data - see extract_player_windows() and
    compute_plus_minus()). Penalties are excluded, and xG is combined
    per-sequence (same-team shots at the same minute) rather than simply
    summed.
  - Notes: definitions/assumptions, kept in sync with this docstring.

WHY THIS LOOKS DIFFERENT FROM whoscored_report.py
--------------------------------------------------
WhoScored/Opta exposes a full event-by-event log (every pass, tackle,
touch, each with x/y coordinates), which is what let the WhoScored report
build Touches/Passing/Defensive-Actions tabs - full possession
reconstruction. FotMob's match data is NOT a full event log. It's a shot
map (every shot, with xG/xGOT) plus a set of aggregated team/player
stats that FotMob itself computes. That's a narrower, differently-shaped
dataset, so this report is scoped to shots/xG plus FotMob's own
aggregate stats, rather than trying to recreate the WhoScored tab set on
data that doesn't exist in that shape here.

SETUP (same pattern as whoscored_report.py)
--------------------------------------------
Requires Selenium + a real Chrome browser via the same utils/driver.py
helper (get_driver()) already used by whoscored_report.py, plus:
    pip install selenium beautifulsoup4 pandas openpyxl

IMPORTANT: this script calls get_driver(track_network=True), not the
plain get_driver() whoscored_report.py uses. That mode (a) runs a real,
VISIBLE (non-headless) Chrome window rather than headless, and (b)
enables Chrome's network/performance logging - both are required for
the network-log capture described below. Expect an actual browser
window to pop up while this runs; that's intentional.

Usage:
    python fotmob_report.py "https://www.fotmob.com/matches/<slug>/<code>#<matchId>"

ANTI-SCRAPING NOTE (important - confirmed by live testing, not just theory)
-----------------------------------------------------------------------------
FotMob's real API host is `apigw.fotmob.com` (the old `www.fotmob.com/api/*`
paths are gone entirely and 404). Calling `apigw.fotmob.com/matchDetails`
directly - with `requests`, or even with `fetch()` executed inside the
browser's own JS context via Selenium - reliably 404s, because the
`x-mas` auth header it requires is generated by FotMob's obfuscated
client bundle through some internal signing path, not just "any fetch
call from the page". Confirmed dead (404, not 401) in practice - don't
waste time re-attempting a direct fetch.

Reading the page's embedded Next.js JSON (a <script id="__NEXT_DATA__">
tag) was tried next and ALSO confirmed unreliable for this project's
actual use case: FotMob's short "team-vs-team" URLs (the
`/matches/<slug>/<shortcode>#<matchId>` form) can have their shortcode
alone default-render whichever meeting between two teams is
chronologically NEXT, ignoring the `#<matchId>` fragment (fragments are
never sent to a server - only client-side JS can act on them). Crucially,
__NEXT_DATA__ is a static, server-render-time snapshot; even once a real
user's browser corrects itself client-side and shows the right match on
screen, that script tag does NOT get rewritten to match - so polling it,
however long, keeps reading the same wrong snapshot. Confirmed by live
testing: 10 polls over 15 seconds, zero change.

The approach that actually works: capture the REAL matchDetails network
response FotMob's own page JS receives once it corrects itself (a
genuine response, with a correctly-generated x-mas header, since it's
FotMob's own code making that request - we're just reading it, not
forging it). This requires Chrome's CDP performance/network logging
(get_driver(track_network=True) already sets the right capability) and
a non-headless session actually running FotMob's real client JS - a
headless session, or one with JavaScript disabled entirely, may never
even MAKE that corrected request, let alone let us observe it. See
_extract_via_network_logs(). Embedded __NEXT_DATA__ polling is kept as a
fallback for the (probably common) case of a pre-rendered, popular match
that never needed a corrective client-side fetch at all.

A second wrinkle, specific to FotMob's short "team-vs-team" URLs (the
`/matches/<slug>/<shortcode>#<matchId>` form): the shortcode alone can
default-render whichever meeting between two teams is chronologically
NEXT, ignoring the `#<matchId>` fragment (fragments are never sent to a
server at all - only client-side JS can act on them). A real browser's
own JS does read that fragment and correct itself, but that correction
also happens as part of the same client-side hydration process, which is
exactly why the polling above matters for BOTH problems at once - see
_matches_target_id(), which is used throughout to confirm the JSON we
finally have is for the actual matchId the URL named, not "whatever
loaded first."

DEBUGGING NOTE
---------------
FotMob's internal JSON schema isn't publicly documented and has already
changed at least once (the 2024 header/host change). Because of that,
this script always writes the raw JSON it ended up using to
fotmob_raw_<matchId>.json next to wherever the workbook is saved, and
prints diagnostics about what it found at each polling attempt. If a run
produces an empty/wrong-looking report, that console output plus the raw
JSON file are the first things to check - a field-extraction helper
(`_get_first`, tries several candidate key names) is used throughout
specifically so small schema drifts don't silently break everything, but
a bigger schema change will need that raw JSON to diagnose.

NOTES / ASSUMPTIONS (kept in sync with the Notes tab)
-------------------------------------------------------
  - Outcome is normalized from FotMob's shot "eventType" field (Goal /
    AttemptSaved -> Saved / Miss -> Off Target / AttemptBlocked ->
    Blocked / Post -> Hit Post / OwnGoal).
  - Body Part is normalized from FotMob's shot "shotType" field.
  - On Target is FotMob's own isOnTarget flag where present, else
    inferred as True for Goal/Saved outcomes.
  - X/Y are left exactly as FotMob reports them (coordinate scale/
    orientation not independently verified yet - flagged for review
    once we see a real raw JSON dump).
  - Total xG per team is the sum of the shot map's xG values for that
    team - this should match (or come very close to) FotMob's own
    published xG stat for the match; worth spot-checking on first run.
  - Any stat FotMob doesn't publish for a given match (e.g. no
    Expected Goals group at lower-profile competitions) will just be
    absent as a column rather than erroring.
"""

import sys
import os
import re
import json
import time
import base64
import argparse

import pandas as pd
from bs4 import BeautifulSoup

from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from utils.driver import get_driver


# ============================================================
# 1. CONFIGURATION / ASSUMPTIONS
# ============================================================
PAGE_LOAD_WAIT_SEC = 20
# FotMob often defers loading match content client-side (see the
# ANTI-SCRAPING NOTE above) - poll the page source this many times, this many
# seconds apart, waiting for the real data to hydrate in before giving up.
HYDRATION_POLL_ATTEMPTS = 10
HYDRATION_POLL_INTERVAL_SEC = 1.5

# FotMob shot "eventType" -> our normalized Outcome label.
OUTCOME_MAP = {
    'Goal': 'Goal',
    'AttemptSaved': 'Saved',
    'Miss': 'Off Target',
    'AttemptBlocked': 'Blocked',
    'Post': 'Hit Post',
    'OwnGoal': 'Own Goal',
}

# FotMob shot "shotType" (body part) -> our label.
BODY_PART_MAP = {
    'LeftFoot': 'Left Foot',
    'RightFoot': 'Right Foot',
    'Head': 'Head',
    'Header': 'Head',
    'OtherBodyPart': 'Other',
}


# ============================================================
# 2. SCRAPE
# ============================================================
def extract_match_id(url: str) -> str:
    """
    FotMob match URLs look like:
        https://www.fotmob.com/matches/<slug>/<shortcode>#<matchId>
    The numeric matchId after the '#' is what the API keys off of.
    """
    m = re.search(r'#(\d+)', url)
    if m:
        return m.group(1)
    m = re.search(r'/(\d+)(?:[/?#]|$)', url)
    if m:
        return m.group(1)
    raise ValueError(
        f"Couldn't find a numeric matchId in URL: {url!r}. "
        "Expected something like '...#4813652' at the end."
    )


def _find_next_data_json(html: str):
    """Look for Next.js's embedded page-data script tag, if present."""
    soup = BeautifulSoup(html, 'html.parser')
    tag = soup.find('script', id='__NEXT_DATA__')
    if tag and tag.string:
        try:
            return json.loads(tag.string)
        except json.JSONDecodeError:
            return None
    return None


def _search_for_key(obj, target_keys, max_depth=25):
    """
    Recursively search a nested dict/list for the first value whose key
    is in `target_keys`. Next.js nests the real API payload under a few
    layers of pageProps/dehydratedState/etc. that can shift between
    FotMob deploys - searching by key name is more resilient than
    hard-coding one exact path.
    """
    stack = [(obj, 0)]
    while stack:
        cur, depth = stack.pop()
        if depth > max_depth:
            continue
        if isinstance(cur, dict):
            for k, v in cur.items():
                if k in target_keys:
                    return v
            for v in cur.values():
                stack.append((v, depth + 1))
        elif isinstance(cur, list):
            for v in cur:
                stack.append((v, depth + 1))
    return None


def _search_for_dicts_with_keys(obj, required_keys, max_depth=25):
    """
    Like _search_for_key() above, but returns EVERY dict containing all of
    `required_keys` instead of just the first value for one key - used by
    find_fotmob_match_url() below, which needs the whole list of that day's
    fixtures, not a single value.
    """
    found = []
    stack = [(obj, 0)]
    while stack:
        cur, depth = stack.pop()
        if depth > max_depth:
            continue
        if isinstance(cur, dict):
            if required_keys.issubset(cur.keys()):
                found.append(cur)
            for v in cur.values():
                stack.append((v, depth + 1))
        elif isinstance(cur, list):
            for v in cur:
                stack.append((v, depth + 1))
    return found


def find_fotmob_match_url(date_str, home_name, away_name):
    """
    Best-effort matcher for the batch runner: loads FotMob's day-schedule
    page for `date_str` (YYYY-MM-DD) and looks for a fixture whose team
    names match `home_name`/`away_name` (via combined_report's
    canonical_team_name(), so 'Man Utd' vs 'Manchester United', 'Spurs' vs
    'Tottenham Hotspur', etc. still match across the two sites' different
    naming), returning a FotMob match URL for it, or None if no match was
    found.

    HONESTY NOTE - READ BEFORE RELYING ON THIS: unlike _extract_via_network_
    logs() above (built and confirmed against a real captured 'matchdetails'
    response), the response this function looks for (anything with 'match'
    in its URL, containing dicts with 'home'/'away' keys) is an educated
    guess at FotMob's day-schedule API shape, not a verified one - there was
    no way to open a browser and inspect the real page/response from the
    environment this was written in. If this returns None for a match you
    know exists on FotMob, that's expected first-try friction for an
    unverified scraper - paste the FotMob URL manually instead (the batch
    runner UI always supports this), and share the day-schedule page's
    captured network responses so this can be corrected against real data,
    the same way every other WhoScored/FotMob schema surprise in this
    project got fixed.

    A local import of combined_report is used here (rather than importing
    it at module level) specifically so fotmob_report.py stays independently
    usable on its own (as fotmob_streamlit_app.py already relies on) for
    everyone NOT using the batch runner - this is the only function in this
    file that needs cross-source team-name matching at all.
    """
    from combined_report import canonical_team_name

    target_home = canonical_team_name(home_name)
    target_away = canonical_team_name(away_name)
    day_url = f"https://www.fotmob.com/matches?date={date_str.replace('-', '')}"

    print(f"Opening {day_url} ...")
    with get_driver(track_network=True) as driver:
        driver.get(day_url)
        WebDriverWait(driver, PAGE_LOAD_WAIT_SEC).until(
            EC.presence_of_element_located((By.TAG_NAME, 'body'))
        )
        time.sleep(HYDRATION_POLL_INTERVAL_SEC * 4)

        try:
            logs = driver.get_log('performance')
        except Exception as e:
            raise RuntimeError(
                f"Couldn't read performance logs (was track_network=True used?): {e}"
            )

    fixture_dicts = []
    for entry in logs:
        try:
            message = json.loads(entry['message'])['message']
        except (KeyError, json.JSONDecodeError, TypeError):
            continue
        if message.get('method') != 'Network.responseReceived':
            continue
        params = message.get('params', {})
        resp_url = params.get('response', {}).get('url', '')
        if 'match' not in resp_url.lower():
            continue
        request_id = params.get('requestId')
        try:
            body = driver.execute_cdp_cmd('Network.getResponseBody', {'requestId': request_id})
        except Exception:
            continue
        text = body.get('body', '')
        if body.get('base64Encoded'):
            try:
                text = base64.b64decode(text).decode('utf-8', errors='replace')
            except Exception:
                continue
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            continue
        fixture_dicts.extend(_search_for_dicts_with_keys(data, {'home', 'away'}))

    print(f"Day-schedule scan: found {len(fixture_dicts)} fixture-like object(s) for {date_str}.")

    for fixture in fixture_dicts:
        home = fixture.get('home')
        away = fixture.get('away')
        h_name = home.get('name') if isinstance(home, dict) else None
        a_name = away.get('name') if isinstance(away, dict) else None
        if not h_name or not a_name:
            continue
        if canonical_team_name(h_name) != target_home or canonical_team_name(a_name) != target_away:
            continue
        match_id = (fixture.get('id') or fixture.get('matchId')
                    or (home.get('id') if isinstance(home, dict) else None))
        if not match_id:
            continue
        slug_home = re.sub(r'[^a-z0-9]+', '-', h_name.lower()).strip('-')
        slug_away = re.sub(r'[^a-z0-9]+', '-', a_name.lower()).strip('-')
        return f"https://www.fotmob.com/matches/{slug_home}-vs-{slug_away}#{match_id}"

    return None


def _get_first(d, keys, default=None):
    """Return the first present, non-None value among several candidate keys."""
    if not isinstance(d, dict):
        return default
    for k in keys:
        if k in d and d[k] is not None:
            return d[k]
    return default


def _shots_list(match_json):
    """Return the actual shots list (possibly empty) found in a match_json blob, or None."""
    shots = _search_for_key(match_json, {'shots'})
    if not shots:
        shotmap = _search_for_key(match_json, {'shotmap'})
        shots = shotmap.get('shots') if isinstance(shotmap, dict) else None
    return shots


def _matches_target_id(match_json, match_id):
    """
    Check whether the matchId embedded IN the JSON payload itself matches the
    matchId we parsed from the URL. This matters because FotMob's server-side
    render for a given slug/shortcode can default to a DIFFERENT match than
    the one named in the URL's '#<matchId>' fragment (fragments are never
    sent to a server at all - they're purely client-side) - e.g. a slug
    shared by a team pair can default-render "whichever meeting is next"
    rather than the specific historical match the fragment points to.
    """
    found_id = _search_for_key(match_json, {'matchId'})
    return found_id is not None and str(found_id) == str(match_id)


def _extract_content_json(next_data):
    """
    Pull the actual match-content dict out of a parsed __NEXT_DATA__ blob.
    Handles both the "populated" shape (props.pageProps.content.{shotmap,
    stats,...}) and the "deferred" shape ({'fetchingLeagueData': True, ...},
    no content yet - see ANTI-SCRAPING NOTE in the module docstring).
    """
    if not next_data:
        return None
    candidate = _search_for_key(next_data, {'content'})
    if isinstance(candidate, dict) and (candidate.get('shotmap') or candidate.get('stats')):
        return candidate
    # Some pages nest shotmap/stats directly rather than under a 'content' key.
    shotmap = _search_for_key(next_data, {'shotmap'})
    if shotmap:
        return next_data
    return None


def _extract_via_network_logs(driver, match_id):
    """
    Read Chrome's captured network traffic (via CDP performance logs, which
    requires the driver to have been created with track_network=True) and
    find FotMob's OWN matchDetails response - the one the page's real,
    fully-hydrated JS made, with a correctly-generated x-mas header. This
    sidesteps needing to fake that header entirely: we're just reading a
    response FotMob's own app already legitimately received.

    Returns the parsed JSON body of the response whose matchId matches
    `match_id`, or None if no such response was captured.
    """
    try:
        logs = driver.get_log('performance')
    except Exception as e:
        print(f"Couldn't read performance logs (was track_network=True used?): {e}")
        return None

    candidates = []  # (requestId, url)
    for entry in logs:
        try:
            message = json.loads(entry['message'])['message']
        except (KeyError, json.JSONDecodeError, TypeError):
            continue
        if message.get('method') != 'Network.responseReceived':
            continue
        params = message.get('params', {})
        resp_url = params.get('response', {}).get('url', '')
        if 'matchdetails' in resp_url.lower():
            candidates.append((params.get('requestId'), resp_url))

    print(f"Network logs: found {len(candidates)} matchDetails-like response(s).")
    best = None
    for request_id, resp_url in candidates:
        try:
            body = driver.execute_cdp_cmd('Network.getResponseBody', {'requestId': request_id})
        except Exception as e:
            print(f"  {resp_url}: couldn't fetch response body ({e})")
            continue
        text = body.get('body', '')
        if body.get('base64Encoded'):
            try:
                text = base64.b64decode(text).decode('utf-8', errors='replace')
            except Exception as e:
                print(f"  {resp_url}: couldn't base64-decode body ({e})")
                continue
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            print(f"  {resp_url}: response body wasn't valid JSON")
            continue
        found_id = _search_for_key(data, {'matchId'})
        found_shots = len(_shots_list(data) or [])
        print(f"  {resp_url} -> matchId={found_id}, shots={found_shots}")
        if str(found_id) == str(match_id):
            return data
        best = best or data  # remember a fallback in case none match exactly
    return best


def scrape_match(url: str, out_dir: str = '.'):
    """
    Loads the FotMob match page in a real (non-headless, network-logging)
    browser and returns the parsed match-content dict plus the matchId.
    Always writes the raw JSON to fotmob_raw_<matchId>.json in out_dir for
    debugging - see the DEBUGGING NOTE in the module docstring.

    Primary method: read the actual matchDetails network response FotMob's
    own page JS received (via _extract_via_network_logs) - this is the only
    approach confirmed to reliably get the RIGHT match's data, since it's a
    genuine response with a correctly-generated x-mas header, not something
    we're trying to reconstruct ourselves. Requires get_driver(track_network=
    True) so Chrome's performance/network logging is enabled AND so a real
    (non-headless) browser actually runs the page's JS - see ANTI-SCRAPING
    NOTE for why headless/JS-disabled sessions can silently show the wrong
    match with no error at all.

    Falls back to polling the page's embedded __NEXT_DATA__ JSON if no
    matching network response was captured (e.g. a pre-rendered match that
    never needed a client-side fetch at all).
    """
    match_id = extract_match_id(url)
    match_json = None
    with get_driver(track_network=True) as driver:
        driver.get(url)
        WebDriverWait(driver, PAGE_LOAD_WAIT_SEC).until(
            EC.presence_of_element_located((By.TAG_NAME, 'body'))
        )
        # Give the page's own JS time to hydrate and make its real request.
        time.sleep(HYDRATION_POLL_INTERVAL_SEC * 4)

        match_json = _extract_via_network_logs(driver, match_id)

        if match_json is None or not _matches_target_id(match_json, match_id):
            print("Network-log extraction didn't find the target match - "
                  "falling back to polling embedded page JSON.")
            for attempt in range(1, HYDRATION_POLL_ATTEMPTS + 1):
                html = driver.page_source
                next_data = _find_next_data_json(html)
                candidate = _extract_content_json(next_data)

                found_id = _search_for_key(candidate, {'matchId'}) if candidate else None
                found_shots = len(_shots_list(candidate) or []) if candidate else 0
                print(f"Hydration poll {attempt}/{HYDRATION_POLL_ATTEMPTS}: "
                      f"found matchId={found_id}, shots={found_shots}, target matchId={match_id}")

                if candidate and (match_json is None or found_shots):
                    match_json = candidate
                if candidate and found_shots and _matches_target_id(candidate, match_id):
                    break
                if attempt < HYDRATION_POLL_ATTEMPTS:
                    time.sleep(HYDRATION_POLL_INTERVAL_SEC)

    if match_json is None:
        raise RuntimeError(
            "Couldn't find match data via either the embedded page JSON or a "
            "browser-side fetch. FotMob likely changed something - re-inspect "
            "the page's Network tab for the matchDetails request and compare "
            "against the DEBUGGING NOTE in this file's module docstring."
        )

    if not _matches_target_id(match_json, match_id):
        print(f"WARNING: final match_json's own matchId doesn't match the target ({match_id}) - "
              "this report is very likely describing the WRONG match. See the fetch debug output "
              "above for why the explicit-matchId fetch didn't take over.")

    os.makedirs(out_dir, exist_ok=True)
    raw_path = os.path.join(out_dir, f'fotmob_raw_{match_id}.json')
    with open(raw_path, 'w') as f:
        json.dump(match_json, f, indent=2)
    print(f"Wrote raw matchDetails JSON to {raw_path} (for debugging).")

    return match_json, match_id


# ============================================================
# 3. TEAM NAME / ID RESOLUTION
# ============================================================
def extract_team_names(match_json):
    """Best-effort home/away team name lookup, tried in a couple of likely spots."""
    header = match_json.get('header') if isinstance(match_json, dict) else None
    teams = header.get('teams') if isinstance(header, dict) else None
    home_name = away_name = None
    if isinstance(teams, list) and len(teams) >= 2:
        home_name = _get_first(teams[0], ['name'])
        away_name = _get_first(teams[1], ['name'])

    general = match_json.get('general') if isinstance(match_json, dict) else None
    if isinstance(general, dict):
        home_team = general.get('homeTeam') or {}
        away_team = general.get('awayTeam') or {}
        home_name = home_name or _get_first(home_team, ['name'])
        away_name = away_name or _get_first(away_team, ['name'])

    # Some responses (observed live) carry team names under a top-level
    # 'lineup' key instead of 'general'/'header'.
    lineup = match_json.get('lineup') if isinstance(match_json, dict) else None
    if isinstance(lineup, dict):
        home_team = lineup.get('homeTeam') or {}
        away_team = lineup.get('awayTeam') or {}
        home_name = home_name or _get_first(home_team, ['name'])
        away_name = away_name or _get_first(away_team, ['name'])

    return home_name, away_name


def _search_for_key_ci(obj, target_keys_lower, max_depth=25):
    """
    Case-insensitive variant of _search_for_key() - needed specifically for
    extract_referee() below. FotMob's content.matchFacts.infoBox is keyed by
    human-readable display labels ('Referee', 'Match Date', 'Tournament',
    'Stadium', 'Attendance' - confirmed against a real match_json dump),
    capitalized like UI text, not the camelCase used for every other key in
    this payload - a plain case-sensitive key search for 'referee' silently
    never matches the real 'Referee' key. target_keys_lower must already be
    all-lowercase; every key encountered is lowercased before comparing.
    """
    stack = [(obj, 0)]
    while stack:
        cur, depth = stack.pop()
        if depth > max_depth:
            continue
        if isinstance(cur, dict):
            for k, v in cur.items():
                if isinstance(k, str) and k.lower() in target_keys_lower:
                    return v
            for v in cur.values():
                stack.append((v, depth + 1))
        elif isinstance(cur, list):
            for v in cur:
                stack.append((v, depth + 1))
    return None


def extract_referee(match_json):
    """
    Referee name lookup for the dashboard's Fixtures tab. CONFIRMED against
    a real live match_json dump (fotmob_raw_5795368.json) - the real shape
    is content.matchFacts.infoBox.Referee -> {'text': 'Michael Oliver',
    'imgUrl': ..., 'countryCode': ..., 'stats': [...]}. Note two things that
    tripped up the first (unverified, guessed) version of this function:
    infoBox's keys are capitalized display labels ('Referee', 'Match Date',
    'Tournament', 'Stadium', 'Attendance'), not the camelCase used
    everywhere else in this payload, so a case-sensitive search for
    'referee' never matched the real 'Referee' key; and the name itself
    lives under 'text', not 'name'/'refereeName' as guessed originally. That
    real match_json had no 'general.referee' at all (general's own keys are
    matchId/matchName/homeTeam/awayTeam/etc, no referee field) - kept below
    as a first check anyway in case a different competition/match does
    carry it there, since it's a cheap check and doesn't cost anything if
    absent. Returns None (never raises) if nothing is found, rather than
    blocking the rest of the match from saving.
    """
    general = match_json.get('general') if isinstance(match_json, dict) else None
    if isinstance(general, dict):
        referee = general.get('referee')
        if isinstance(referee, dict):
            name = _get_first(referee, ['text', 'name', 'refereeName'])
            if name:
                return name
        elif isinstance(referee, str) and referee.strip():
            return referee.strip()

    # Confirmed real spot - see docstring above.
    info_box = _search_for_key(match_json, {'infoBox'})
    if isinstance(info_box, dict):
        referee = info_box.get('Referee')
        if isinstance(referee, dict):
            name = _get_first(referee, ['text', 'name', 'refereeName'])
            if name:
                return name
        elif isinstance(referee, str) and referee.strip():
            return referee.strip()

    # Case-insensitive fallback, in case a different match/competition nests
    # this somewhere other than infoBox, or under different capitalization.
    found = _search_for_key_ci(match_json, {'referee', 'refereename'})
    if isinstance(found, dict):
        return _get_first(found, ['text', 'name', 'refereeName'])
    if isinstance(found, str) and found.strip():
        return found.strip()
    return None


def extract_team_id_map(match_json):
    """Map FotMob teamId -> team name, since shots are keyed by teamId, not name."""
    mapping = {}

    def _add(team):
        tid = _get_first(team, ['id', 'teamId'])
        name = _get_first(team, ['name'])
        if tid is not None and name:
            mapping[tid] = name
            mapping[str(tid)] = name  # ids sometimes show up as strings on shots

    general = match_json.get('general') if isinstance(match_json, dict) else None
    if isinstance(general, dict):
        _add(general.get('homeTeam') or {})
        _add(general.get('awayTeam') or {})

    # Fallback observed live: team names/ids live under a top-level 'lineup' key.
    lineup = match_json.get('lineup') if isinstance(match_json, dict) else None
    if isinstance(lineup, dict):
        _add(lineup.get('homeTeam') or {})
        _add(lineup.get('awayTeam') or {})

    return mapping


def extract_match_status_hint(match_json):
    """
    Best-effort human-readable note about the match's status, used to explain
    an empty Shots tab (most commonly: the match just hasn't been played yet).
    """
    info_box = _search_for_key(match_json, {'infoBox'}) or {}
    date_info = info_box.get('Match Date') if isinstance(info_box, dict) else None
    parts = []
    if isinstance(date_info, dict):
        utc_time = date_info.get('utcTime')
        tbd = date_info.get('matchDateTbd')
        if utc_time:
            parts.append(f"scheduled kickoff: {utc_time}{' (date TBD)' if tbd else ''}")
    events = _search_for_key(match_json, {'events'})
    if isinstance(events, dict) and events.get('ongoing') and not events.get('events'):
        parts.append("no events recorded yet")
    return "; ".join(parts) if parts else None


# ============================================================
# 4. SHOTS (SHOT MAP)
# ============================================================
def compute_shots(match_json):
    """One row per shot, across both teams, sorted chronologically."""
    shots = _search_for_key(match_json, {'shots'})
    if not shots:
        shotmap = _search_for_key(match_json, {'shotmap'})
        shots = shotmap.get('shots') if isinstance(shotmap, dict) else None

    columns = ['Team', 'Player', 'Minute', 'Added Time', 'Period', 'Situation',
               'Body Part', 'Outcome', 'On Target', 'xG', 'xGOT', 'X', 'Y']
    if not shots:
        return pd.DataFrame(columns=columns)

    team_map = extract_team_id_map(match_json)

    rows = []
    for s in shots:
        team_id = _get_first(s, ['teamId'])
        team_name = team_map.get(team_id, str(team_id))
        event_type = _get_first(s, ['eventType'])
        outcome = OUTCOME_MAP.get(event_type, event_type)
        body_part_raw = _get_first(s, ['shotType'])
        body_part = BODY_PART_MAP.get(body_part_raw, body_part_raw)
        on_target_flag = _get_first(s, ['isOnTarget'])
        on_target = bool(on_target_flag) if on_target_flag is not None else outcome in {'Goal', 'Saved'}
        rows.append({
            'Team': team_name,
            'Player': _get_first(s, ['playerName', 'name']),
            'Minute': _get_first(s, ['min', 'minute']),
            'Added Time': _get_first(s, ['minAdded', 'minuteAdded'], 0),
            'Period': _get_first(s, ['period']),
            'Situation': _get_first(s, ['situation']),
            'Body Part': body_part,
            'Outcome': outcome,
            'On Target': on_target,
            'xG': _get_first(s, ['expectedGoals', 'xg', 'xG']),
            'xGOT': _get_first(s, ['expectedGoalsOnTarget', 'xgot', 'xGOT']),
            'X': _get_first(s, ['x']),
            'Y': _get_first(s, ['y']),
        })

    df = pd.DataFrame(rows, columns=columns)
    sort_cols = [c for c in ['Minute', 'Added Time'] if c in df.columns]
    if sort_cols:
        df = df.sort_values(sort_cols, na_position='last').reset_index(drop=True)
    return df


# ============================================================
# 5. TOTALS (ROLLED-UP + FOTMOB'S OWN STAT GROUPS)
# ============================================================
def compute_totals(match_json, shots_df, home_name, away_name):
    """
    Team-level Totals tab: Shots/Shots on Target/Goals/Total xG rolled up
    from the shot map, plus whichever aggregate stat groups FotMob itself
    published for this match (possession, corners, fouls, cards, passes,
    etc. - varies by competition/match).
    """
    teams_order = [t for t in [home_name, away_name] if t] or sorted(shots_df['Team'].dropna().unique())
    totals = pd.DataFrame({'team': teams_order}).set_index('team')

    if not shots_df.empty:
        agg = shots_df.groupby('Team').agg(
            Shots=('Outcome', 'size'),
            **{'Shots on Target': ('On Target', 'sum')},
            Goals=('Outcome', lambda s: int((s == 'Goal').sum())),
            **{'Total xG': ('xG', 'sum')},
            **{'Total post-shot xG': ('xGOT', 'sum')},
        )
        totals = totals.join(agg, how='left')

    totals = totals.fillna(0)
    for c in ['Shots', 'Shots on Target', 'Goals']:
        if c in totals.columns:
            totals[c] = totals[c].astype(int)
    for c in ['Total xG', 'Total post-shot xG']:
        if c in totals.columns:
            totals[c] = totals[c].round(2)

    # FotMob's own published match-stat groups, if present. Confirmed live
    # path is content.stats.Periods.All.stats[] (each entry: {title, key,
    # stats: [home, away], format, type}) - fall back to a couple of looser
    # lookups in case that nesting shifts again.
    stat_groups = None
    stats_root = match_json.get('stats') if isinstance(match_json, dict) else None
    if isinstance(stats_root, dict):
        periods = stats_root.get('Periods')
        all_period = periods.get('All') if isinstance(periods, dict) else None
        if isinstance(all_period, dict) and isinstance(all_period.get('stats'), list):
            stat_groups = all_period['stats']
        elif isinstance(stats_root.get('stats'), list):
            stat_groups = stats_root['stats']
    if stat_groups is None:
        generic = _search_for_key(match_json, {'stats'})
        stat_groups = generic if isinstance(generic, list) else None
    if isinstance(stat_groups, list):
        for group in stat_groups:
            group_stats = _get_first(group, ['stats']) if isinstance(group, dict) else None
            if not isinstance(group_stats, list):
                continue
            for stat in group_stats:
                title = _get_first(stat, ['title', 'key'])
                values = _get_first(stat, ['stats', 'values'])
                if not title or not isinstance(values, list) or len(values) < 2:
                    continue
                if title in totals.columns:
                    continue  # already set from an earlier group - keep first occurrence
                home_val, away_val = values[0], values[1]
                # Some stat entries wrap each value as {'value': X, ...}.
                if isinstance(home_val, dict):
                    home_val = home_val.get('value', home_val)
                if isinstance(away_val, dict):
                    away_val = away_val.get('value', away_val)
                if home_name in totals.index:
                    totals.loc[home_name, title] = home_val
                if away_name in totals.index:
                    totals.loc[away_name, title] = away_val

    totals = totals.reindex(teams_order).reset_index()
    return totals


# ============================================================
# 5b. SHOT BREAKDOWN (by player / situation / body part)
# ============================================================
SHOT_BREAKDOWN_DIMENSIONS = [
    ('By Player', 'Player'),
    ('By Situation', 'Situation'),
    ('By Body Part', 'Body Part'),
]
# FotMob's own flat expected-goals value for any penalty kick, regardless of
# what (if anything) the shot map's own per-shot xG field happens to record
# for it - used to back a penalty's xG out of a group's total (see
# compute_shot_breakdowns() below) rather than trusting that field directly.
PENALTY_XG = 0.79


def extract_player_xa(match_json):
    """
    Per-player expected assists (xA) for this match - FotMob's own figure,
    not derived from our shot map (our shot map has no assist/passer field
    to compute xA from ourselves). Read from FotMob's per-player match stat
    groups (content.playerStats, keyed by playerId - each value has a
    'stats' list of groups, each group's 'stats' a dict keyed by stat label
    to {key, stat: {value, ...}}). Looked up by matching a stat whose key or
    label contains "expected assist" (covers however FotMob titles/keys it,
    e.g. 'expected_assists' / 'Expected assists (xA)'). Players who didn't
    play (stats: []) are skipped. Returns columns: Team, Player, xA.
    """
    columns = ['Team', 'Player', 'xA']
    player_stats = match_json.get('playerStats') if isinstance(match_json, dict) else None
    if not isinstance(player_stats, dict):
        player_stats = _search_for_key(match_json, {'playerStats'})
    if not isinstance(player_stats, dict):
        return pd.DataFrame(columns=columns)

    team_map = extract_team_id_map(match_json)
    rows = []
    for pdata in player_stats.values():
        if not isinstance(pdata, dict):
            continue
        stat_groups = pdata.get('stats')
        if not stat_groups:
            continue  # didn't play
        xa_value = None
        for group in stat_groups:
            group_stats = group.get('stats') if isinstance(group, dict) else None
            if not isinstance(group_stats, dict):
                continue
            for label, entry in group_stats.items():
                if not isinstance(entry, dict):
                    continue
                key = str(entry.get('key', '')).lower()
                if 'expected_assist' in key or 'expected assist' in str(label).lower():
                    stat_obj = entry.get('stat')
                    val = stat_obj.get('value') if isinstance(stat_obj, dict) else None
                    if val is not None:
                        xa_value = val
                    break
            if xa_value is not None:
                break
        if xa_value is None:
            continue
        team_id = pdata.get('teamId')
        rows.append({
            'Team': team_map.get(team_id, pdata.get('teamName') or str(team_id)),
            'Player': pdata.get('name'),
            'xA': xa_value,
        })

    return pd.DataFrame(rows, columns=columns)


def extract_player_minutes(match_json):
    """
    Per-player minutes played for this match - FotMob's own figure, read the
    same way as extract_player_xa() (content.playerStats, keyed by playerId -
    each value has a 'stats' list of groups, each group's 'stats' a dict
    keyed by stat label to {key, stat: {value, ...}}). Looked up by matching
    the 'top_stats' group's "Minutes played" entry (key 'minutes_played').
    Players who didn't play (stats: []) are skipped. Returns columns: Team,
    Player, Minutes Played.
    """
    columns = ['Team', 'Player', 'Minutes Played']
    player_stats = match_json.get('playerStats') if isinstance(match_json, dict) else None
    if not isinstance(player_stats, dict):
        player_stats = _search_for_key(match_json, {'playerStats'})
    if not isinstance(player_stats, dict):
        return pd.DataFrame(columns=columns)

    team_map = extract_team_id_map(match_json)
    rows = []
    for pdata in player_stats.values():
        if not isinstance(pdata, dict):
            continue
        stat_groups = pdata.get('stats')
        if not stat_groups:
            continue  # didn't play
        minutes_value = None
        for group in stat_groups:
            group_stats = group.get('stats') if isinstance(group, dict) else None
            if not isinstance(group_stats, dict):
                continue
            for label, entry in group_stats.items():
                if not isinstance(entry, dict):
                    continue
                key = str(entry.get('key', '')).lower()
                if key == 'minutes_played' or str(label).lower() == 'minutes played':
                    stat_obj = entry.get('stat')
                    val = stat_obj.get('value') if isinstance(stat_obj, dict) else None
                    if val is not None:
                        minutes_value = val
                    break
            if minutes_value is not None:
                break
        if minutes_value is None:
            continue
        team_id = pdata.get('teamId')
        rows.append({
            'Team': team_map.get(team_id, pdata.get('teamName') or str(team_id)),
            'Player': pdata.get('name'),
            'Minutes Played': minutes_value,
        })

    return pd.DataFrame(rows, columns=columns)


def extract_player_windows(match_json, player_minutes=None, shots_df=None):
    """
    Per-player on-pitch window for this match: Team, Player, start_minute,
    end_minute, Minutes Played, subbed_off. Backs the Plus Minus tab (see
    compute_plus_minus() below) - it's the "which minutes was this player
    actually on the pitch for" data that FotMob's shot map alone can't
    answer.

    Read from FotMob's own lineup data (content.lineup.homeTeam/awayTeam,
    each with 'starters' + 'subs' lists). Each player's own
    'performance.substitutionEvents' list carries a 'subIn' and/or 'subOut'
    entry with its own 'time' (in minutes) when applicable.

    start_minute is that player's 'subIn' time if they came on as a
    substitute, else 0 (they started the match). end_minute is their
    'subOut' time if they were substituted off - this case needs nothing
    else, since sub_in/sub_out times alone fully define their window.
    Otherwise (played to the final whistle - a starter never subbed off,
    or a substitute who stayed on) end_minute is start_minute + however
    many minutes they're known to have played: preferably FotMob's own
    per-player Minutes Played figure (from extract_player_minutes, passed
    in via player_minutes or computed here if not given) since that
    already correctly accounts for stoppage time; but FotMob's per-player
    stats (unlike the shot map) are sometimes missing or incomplete, most
    often for a very recently finished match FotMob hasn't fully processed
    yet - when that per-player figure isn't available for a player who
    otherwise clearly appeared (has a lineup rating, or a sub event),
    end_minute falls back to a match-wide estimate instead: the latest
    effective minute (Minute + Added Time) seen anywhere on the shot map
    (passed in via shots_df), or a flat 90 if there's no shot map either.
    That fallback is necessarily an approximation - it can't know about
    stoppage time beyond whatever the shot map itself shows - which is
    why FotMob's own figure is always preferred when it's there.

    subbed_off (bool) tells compute_plus_minus() how to treat the boundary
    at end_minute: a player who WAS subbed off doesn't get credit for the
    exact minute they left (that minute belongs to whoever replaced them),
    while a player who finished the match does get credit for the final
    minute itself (so a stoppage-time shot at the very end still counts
    for them).

    Bench players who never actually appeared (no lineup rating, no sub
    event, and no resolvable Minutes Played figure) are skipped entirely -
    there's no on-pitch window to give them. If FotMob returns no lineup
    detail at all for this match (a bare team name/id with no starters/
    subs lists - this does happen, most often for a match FotMob hasn't
    finished processing), this returns an empty DataFrame; there is
    nothing to fall back to in that case since there's no per-player data
    of any kind to start from.
    """
    columns = ['Team', 'Player', 'start_minute', 'end_minute', 'Minutes Played', 'subbed_off']
    lineup = match_json.get('lineup') if isinstance(match_json, dict) else None
    if not isinstance(lineup, dict):
        # Some responses nest lineup under a 'content' key instead of
        # carrying it top-level (same shape variance _shots_list/
        # extract_player_xa already handle) - fall back to a full search
        # before concluding there's really no lineup data at all.
        lineup = _search_for_key(match_json, {'lineup'})
    if not isinstance(lineup, dict):
        return pd.DataFrame(columns=columns)

    if player_minutes is None:
        player_minutes = extract_player_minutes(match_json)
    minutes_lookup = {(r['Team'], r['Player']): r['Minutes Played'] for _, r in player_minutes.iterrows()}

    fallback_end = 90.0
    if shots_df is not None and not shots_df.empty:
        eff = shots_df['Minute'].fillna(0) + shots_df['Added Time'].fillna(0)
        if len(eff):
            fallback_end = max(fallback_end, eff.max())

    rows = []
    for side_key in ('homeTeam', 'awayTeam'):
        side = lineup.get(side_key)
        if not isinstance(side, dict):
            continue
        team_name = side.get('name')
        players = (side.get('starters') or []) + (side.get('subs') or [])
        for p in players:
            if not isinstance(p, dict):
                continue
            name = p.get('name')
            perf = p.get('performance') or {}
            sub_events = perf.get('substitutionEvents') or []
            sub_in = next((e.get('time') for e in sub_events if e.get('type') == 'subIn'), None)
            sub_out = next((e.get('time') for e in sub_events if e.get('type') == 'subOut'), None)
            rating = perf.get('rating')
            minutes_played = minutes_lookup.get((team_name, name))

            appeared = minutes_played is not None or sub_in is not None or sub_out is not None or rating is not None
            if not appeared:
                continue  # never actually appeared (unused bench player)

            start = sub_in if sub_in is not None else 0
            subbed_off = sub_out is not None
            if subbed_off:
                end = sub_out
            elif minutes_played is not None:
                end = start + minutes_played
            else:
                end = fallback_end  # FotMob's own per-player total wasn't available - best effort

            rows.append({
                'Team': team_name, 'Player': name,
                'start_minute': start, 'end_minute': end,
                'Minutes Played': round(minutes_played) if minutes_played is not None else round(end - start),
                'subbed_off': subbed_off,
            })

    return pd.DataFrame(rows, columns=columns)


def compute_plus_minus(shots_df, player_windows, home_name=None, away_name=None):
    """
    Plus Minus tab: for every player, totals of Goals For/Against, Shots
    For/Against, and xG For/Against for exactly the minutes they were on
    the pitch (their window from extract_player_windows() above) - the
    shot/goal/xG state that existed specifically while that player was out
    there, not the match's grand total. E.g. if a player is subbed off
    having played 70 minutes, their row shows the totals through that 70th
    minute; whoever replaces them shows the totals for the remaining
    minutes of the match.

    Penalties are excluded from every one of these six columns (Situation
    == 'Penalty') - the same treatment as the Shot Breakdown tab, and for
    the same reason: a penalty isn't a shot in the run-of-play sense.

    xG For/Against is NOT a simple sum of each shot's own xG value. Shots
    by the SAME team at the exact same effective minute (Minute + Added
    Time) are treated as one sequence - almost certainly a rebound/scramble
    in the same phase of play, since FotMob's shot map carries no separate
    possession/sequence ID to group on more precisely - and combined into a
    single probability (1 minus the product of (1 - xG) across that
    sequence's shots) rather than added together, since simply summing
    individual shot xG values overstates the true combined chance of
    scoring from one spell of play. Shots in different minutes are treated
    as independent and their (already sequence-combined) values are simply
    added together as usual.

    Returns one DataFrame with a Team column - split into two tables, one
    per team, when written to the workbook/UI (see build_workbook()).
    Columns: Team, Player, Minutes Played, Goals For, Goals Against, Shots,
    Shots Against, xG, xG Against.
    """
    out_cols = ['Team', 'Player', 'Minutes Played', 'Goals For', 'Goals Against',
                'Shots', 'Shots Against', 'xG', 'xG Against']
    if shots_df.empty or player_windows.empty:
        return pd.DataFrame(columns=out_cols)

    work = shots_df[shots_df['Situation'] != 'Penalty'].copy()
    work['xG'] = work['xG'].fillna(0.0)
    work['Minute'] = work['Minute'].fillna(0)
    work['Added Time'] = work['Added Time'].fillna(0)
    work['_effective_minute'] = work['Minute'] + work['Added Time']

    # Sequence-combine xG: shots by the same team at the exact same
    # effective minute become one combined probability, not a plain sum.
    seq = (work.groupby(['Team', '_effective_minute'])['xG']
           .apply(lambda xs: 1 - (1 - xs).prod())
           .reset_index(name='seq_xG'))

    teams_all = ([t for t in [home_name, away_name] if t is not None]
                 or sorted(player_windows['Team'].dropna().unique()))
    opponent = {teams_all[0]: teams_all[1], teams_all[1]: teams_all[0]} if len(teams_all) == 2 else {}

    records = []
    for _, prow in player_windows.iterrows():
        team = prow['Team']
        opp = opponent.get(team)
        start, end, subbed_off = prow['start_minute'], prow['end_minute'], prow['subbed_off']

        if subbed_off:
            mask = lambda m: (m >= start) & (m < end)
        else:
            mask = lambda m: (m >= start) & (m <= end)

        own_shots = work[(work['Team'] == team) & mask(work['_effective_minute'])]
        opp_shots = work[(work['Team'] == opp) & mask(work['_effective_minute'])] if opp else work.iloc[0:0]
        own_seq = seq[(seq['Team'] == team) & mask(seq['_effective_minute'])]
        opp_seq = seq[(seq['Team'] == opp) & mask(seq['_effective_minute'])] if opp else seq.iloc[0:0]

        records.append({
            'Team': team,
            'Player': prow['Player'],
            'Minutes Played': prow['Minutes Played'],
            'Goals For': int((own_shots['Outcome'] == 'Goal').sum()),
            'Goals Against': int((opp_shots['Outcome'] == 'Goal').sum()),
            'Shots': int(len(own_shots)),
            'Shots Against': int(len(opp_shots)),
            'xG': round(own_seq['seq_xG'].sum(), 2),
            'xG Against': round(opp_seq['seq_xG'].sum(), 2),
        })

    out = pd.DataFrame(records, columns=out_cols)
    out = out.sort_values(['Team', 'Minutes Played'], ascending=[True, False]).reset_index(drop=True)
    return out


def compute_shot_breakdowns(shots_df, player_xa=None, player_minutes=None):
    """
    Roll the shot map up along a few dimensions - by player, by situation
    (open play / set piece / penalty / corner / fast break, per FotMob's own
    'situation' field), and by body part - each broken out per team. Every
    breakdown uses the same Shots / Goals / Total xG columns as the Totals
    tab (minus Shots on Target - not carried on this tab), just at a finer
    grain. If player_xa (from extract_player_xa) is supplied, an extra xA
    column is merged onto the 'By Player' table only - it's a per-player
    stat, not something the other two dimensions (situation/body part) can
    meaningfully carry. Likewise, if player_minutes (from
    extract_player_minutes) is supplied, a Minutes Played column is merged
    onto the 'By Player' table only, placed directly to the right of Player
    (before Shots).

    Penalties are excluded from Shots / Goals / Total xG everywhere on this
    tab - a penalty kick isn't a shot in the run-of-play sense, so it
    shouldn't inflate a player's/team's shot volume, expected goals, or
    actual goals tally. A group's Total xG is computed as that group's full
    xG total (every shot, penalties included) minus PENALTY_XG (FotMob's own
    flat 0.79 expected-goals value for any penalty) times however many
    penalties are in that group - rather than simply summing only the
    non-penalty shots' own xG figures - so the result doesn't depend on
    whatever value the shot map's own xG field happens to carry for a
    penalty. A group made up entirely of penalties (most notably the
    'Penalty' row that would otherwise appear on the By Situation table)
    drops out of its breakdown entirely, since after this exclusion it would
    only ever show up as an all-zero row.

    Any player with xA > 0 is included on the 'By Player' table even if they
    took zero (non-penalty) shots (e.g. a player who set up a good chance but
    didn't shoot themselves) - their Shots/Goals/Total xG all show 0 in that
    case.

    Returns an ordered dict: {'By Player': df, 'By Situation': df, 'By Body
    Part': df}, each sorted by team then descending shot count.
    """
    breakdowns = {}
    for label, group_col in SHOT_BREAKDOWN_DIMENSIONS:
        cols = ['Team', group_col, 'Shots', 'Goals', 'Total xG']
        if label == 'By Player':
            out_cols = ['Team', group_col, 'Minutes Played', 'Shots', 'Goals', 'Total xG', 'xA']
        else:
            out_cols = cols
        if shots_df.empty or group_col not in shots_df.columns:
            agg = pd.DataFrame(columns=cols)
        else:
            work = shots_df.dropna(subset=[group_col]).copy()
            if work.empty:
                agg = pd.DataFrame(columns=cols)
            else:
                work['xG'] = work['xG'].fillna(0.0)
                is_pen = work['Situation'] == 'Penalty'
                non_pen = work[~is_pen]

                if non_pen.empty:
                    agg = pd.DataFrame(columns=cols)
                else:
                    group_keys = ['Team', group_col]
                    total_xg_all = work.groupby(group_keys)['xG'].sum()
                    pen_counts = is_pen.groupby([work['Team'], work[group_col]]).sum()

                    agg = non_pen.groupby(group_keys).agg(
                        Shots=('Outcome', 'size'),
                        Goals=('Outcome', lambda s: int((s == 'Goal').sum())),
                    ).reset_index()
                    agg = agg.set_index(group_keys)
                    non_pen_xg = (total_xg_all.reindex(agg.index).fillna(0.0)
                                  - PENALTY_XG * pen_counts.reindex(agg.index).fillna(0))
                    agg['Total xG'] = non_pen_xg.clip(lower=0).round(2)
                    agg = agg.reset_index()
                    agg = agg[cols]

        if label == 'By Player':
            if player_xa is not None and not player_xa.empty:
                agg = agg.merge(player_xa, how='left', on=['Team', 'Player'])
            else:
                agg['xA'] = 0.0
            agg['xA'] = agg['xA'].fillna(0.0).round(2)

            if player_minutes is not None and not player_minutes.empty:
                agg = agg.merge(player_minutes, how='left', on=['Team', 'Player'])
            else:
                agg['Minutes Played'] = None

            # Add zero-shot rows for any player with xA > 0 who isn't already
            # in the table (took no shots themselves, but created a chance).
            if player_xa is not None and not player_xa.empty:
                existing = set(zip(agg['Team'], agg['Player']))
                extra = player_xa[
                    (player_xa['xA'] > 0)
                    & ~player_xa.apply(lambda r: (r['Team'], r['Player']) in existing, axis=1)
                ].copy()
                if not extra.empty:
                    extra['Shots'] = 0
                    extra['Goals'] = 0
                    extra['Total xG'] = 0.0
                    extra['xA'] = extra['xA'].round(2)
                    if player_minutes is not None and not player_minutes.empty:
                        extra = extra.merge(player_minutes, how='left', on=['Team', 'Player'])
                    else:
                        extra['Minutes Played'] = None
                    agg = pd.concat([agg, extra[out_cols]], ignore_index=True)

        agg = agg.sort_values(['Team', 'Shots'], ascending=[True, False]).reset_index(drop=True)
        breakdowns[label] = agg[out_cols]
    return breakdowns


# ============================================================
# 5c. xG BREAKDOWN (by half, by phase) - second table on the Totals tab
# ============================================================
# FotMob's shot "situation" values that count as a set piece (a stopped-ball
# restart) - anything else (RegularPlay, FastBreak, etc.) counts as Open Play.
SET_PIECE_SITUATIONS = {'SetPiece', 'FromCorner', 'Penalty'}
# Extra-time periods get lumped into "2nd Half" rather than dropped, since
# most matches never reach extra time and dropping them silently would be
# worse than this simplification for the rare cup match that does.
SECOND_HALF_PERIODS = {'SecondHalf', 'FirstExtraHalf', 'SecondExtraHalf'}


def compute_xg_breakdown(shots_df, home_name, away_name):
    """
    Team-level shots and xG split two different ways: by half (1st/2nd, from
    FotMob's 'period' field) and by phase (Open Play vs Set Piece, from
    FotMob's 'situation' field - see SET_PIECE_SITUATIONS above for exactly
    which situations count as a set piece). The half columns (shots and xG)
    and the phase columns (xG only) are independent cuts of the same shot
    map, not mutually exclusive categories of each other - e.g. a set piece
    goal in the 2nd half adds to both '2nd Half xG' and 'Set Piece xG'.
    """
    teams_order = [t for t in [home_name, away_name] if t] or sorted(shots_df['Team'].dropna().unique())
    count_cols = ['1st Half Shots', '2nd Half Shots']
    xg_cols = ['1st Half xG', '2nd Half xG', 'Open Play xG', 'Set Piece xG']
    cols = count_cols + xg_cols
    out = pd.DataFrame({'team': teams_order}).set_index('team')
    for c in count_cols:
        out[c] = 0
    for c in xg_cols:
        out[c] = 0.0

    if not shots_df.empty:
        work = shots_df.copy()
        work['xG'] = work['xG'].fillna(0.0)

        first_half_mask = work['Period'] == 'FirstHalf'
        second_half_mask = work['Period'].isin(SECOND_HALF_PERIODS)
        is_set_piece = work['Situation'].isin(SET_PIECE_SITUATIONS)

        first_half_shots = work[first_half_mask].groupby('Team').size()
        second_half_shots = work[second_half_mask].groupby('Team').size()
        first_half_xg = work[first_half_mask].groupby('Team')['xG'].sum()
        second_half_xg = work[second_half_mask].groupby('Team')['xG'].sum()
        set_piece_xg = work[is_set_piece].groupby('Team')['xG'].sum()
        open_play_xg = work[~is_set_piece].groupby('Team')['xG'].sum()

        for col, series in [('1st Half Shots', first_half_shots), ('2nd Half Shots', second_half_shots)]:
            out[col] = series.reindex(out.index).fillna(0).astype(int)
        for col, series in [('1st Half xG', first_half_xg), ('2nd Half xG', second_half_xg),
                             ('Open Play xG', open_play_xg), ('Set Piece xG', set_piece_xg)]:
            out[col] = series.reindex(out.index).fillna(0.0)

    for c in xg_cols:
        out[c] = out[c].round(2)
    out = out.reindex(teams_order).reset_index()
    return out


# ============================================================
# 6. WRITE WORKBOOK
# ============================================================
HEADER_FONT = Font(name='Arial', bold=True, color='FFFFFF')
HEADER_FILL = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')


def write_table(ws, df, start_row=1):
    for j, col in enumerate(df.columns, start=1):
        c = ws.cell(row=start_row, column=j, value=col)
        c.font = HEADER_FONT
        c.fill = HEADER_FILL
        c.alignment = Alignment(horizontal='center')
    for i, row in enumerate(df.itertuples(index=False), start=start_row + 1):
        for j, val in enumerate(row, start=1):
            ws.cell(row=i, column=j, value=val)
    return start_row + len(df) + 1


def autosize(ws, min_width=10, max_width=40):
    for col_cells in ws.columns:
        length = max((len(str(c.value)) for c in col_cells if c.value is not None), default=0)
        letter = get_column_letter(col_cells[0].column)
        ws.column_dimensions[letter].width = max(min_width, min(max_width, length + 2))


def build_workbook(shots_df, totals_df, home_name, away_name, match_id, shot_breakdowns=None,
                    xg_breakdown=None, plus_minus=None):
    wb = Workbook()

    ws_totals = wb.active
    ws_totals.title = 'Totals'
    row = write_table(ws_totals, totals_df, start_row=1)
    if xg_breakdown is not None:
        row += 1
        c = ws_totals.cell(row=row, column=1, value='xG Breakdown (by half, by phase)')
        c.font = Font(name='Arial', bold=True, size=12)
        row += 1
        write_table(ws_totals, xg_breakdown, start_row=row)
    autosize(ws_totals)

    ws_shots = wb.create_sheet('Shots')
    write_table(ws_shots, shots_df)
    autosize(ws_shots)

    if shot_breakdowns:
        ws_breakdown = wb.create_sheet('Shot Breakdown')
        row = 1
        for label, df in shot_breakdowns.items():
            teams_for_breakdown = ([t for t in [home_name, away_name] if t is not None]
                                    or sorted(df['Team'].dropna().unique()))
            for t in teams_for_breakdown:
                t_df = df[df['Team'] == t].drop(columns=['Team']).reset_index(drop=True)
                c = ws_breakdown.cell(row=row, column=1, value=f'{t} - {label}')
                c.font = Font(name='Arial', bold=True, size=12)
                row += 1
                row = write_table(ws_breakdown, t_df, start_row=row)
                row += 1  # blank row between tables
        autosize(ws_breakdown)

    if plus_minus is not None and not plus_minus.empty:
        ws_pm = wb.create_sheet('Plus Minus')
        teams_for_pm = ([t for t in [home_name, away_name] if t is not None]
                         or sorted(plus_minus['Team'].dropna().unique()))
        row = 1
        for t in teams_for_pm:
            t_pm = plus_minus[plus_minus['Team'] == t].drop(columns=['Team']).reset_index(drop=True)
            c = ws_pm.cell(row=row, column=1, value=f'{t} - Plus Minus')
            c.font = Font(name='Arial', bold=True, size=12)
            row += 1
            row = write_table(ws_pm, t_pm, start_row=row)
            row += 1  # blank row between tables
        autosize(ws_pm)

    ws_notes = wb.create_sheet('Notes')
    notes = [
        f"FotMob Match Report - matchId {match_id} ({home_name} vs {away_name})",
        "",
        "Shots tab: one row per shot from FotMob's shot map. Outcome is normalized from"
        " FotMob's 'eventType' field (Goal / AttemptSaved -> Saved / Miss -> Off Target /"
        " AttemptBlocked -> Blocked / Post -> Hit Post / OwnGoal). Body Part is normalized"
        " from FotMob's 'shotType' field. On Target uses FotMob's own isOnTarget flag where"
        " present, else is inferred as True for Goal/Saved outcomes.",
        "",
        "xG / xGOT are read directly from FotMob's shot map (their own model's values, not"
        " independently recomputed here).",
        "",
        "X / Y are left exactly as FotMob reports them - the coordinate scale/orientation"
        " hasn't been independently verified yet against a known reference; worth a sanity"
        " check against the match's actual shot chart before relying on them for plotting.",
        "",
        "Totals tab: Shots / Shots on Target / Goals / Total xG / Total post-shot xG are rolled"
        " up directly from the Shots tab (Total xG is the sum of that team's shot-map xG values -"
        " this should be very close to FotMob's own published xG stat for the match, worth"
        " spot-checking on first run; Total post-shot xG is the sum of xGOT - FotMob's expected"
        " goals ON TARGET model, i.e. based on where the shot actually went rather than pre-shot"
        " quality alone - so it only reflects shots that were on target, unlike Total xG which"
        " covers every shot). All other columns are whichever aggregate stat groups FotMob itself"
        " published for this specific match (varies by competition/match - lower-profile"
        " matches may be missing groups like Expected Goals or Big Chances).",
        "",
        "Shot Breakdown tab: Shots/Goals/Total xG (no Shots on Target here - just Shots, Goals,"
        " and Total xG), rolled up along three dimensions - By Player, By Situation (FotMob's own"
        " categorization: RegularPlay, FastBreak, SetPiece, FromCorner, Penalty, etc.), and By Body"
        " Part - each split into two separate tables, one per team, rather than one combined table"
        " with a Team column. Unlike the Totals tab, EVERY penalty is excluded from these"
        " columns here - a penalty kick isn't a shot in the run-of-play sense, so it doesn't count"
        " as a Shot or a Goal on this tab, and its xG isn't included in Total xG either (so these"
        " numbers will intentionally be lower than the Totals tab's for a match with any"
        " penalties). Total xG for a group is that group's full xG total (every shot, penalties"
        " included) minus 0.79 - FotMob's own flat expected-goals value for any penalty - times"
        " however many penalties were in that group, rather than simply summing the non-penalty"
        " shots' own xG figures, so the result doesn't depend on whatever the shot map's own xG"
        " field happens to carry for a penalty. A group made up entirely of penalties (most notably"
        " the 'Penalty' row that would otherwise appear on the By Situation table) drops out of its"
        " breakdown entirely, since it would only ever show up as an all-zero row after this"
        " exclusion. Shots missing that dimension's value are dropped from that particular"
        " breakdown (rare). The By Player table additionally has a Minutes Played column (directly"
        " to the right of Player) and an xA (expected assists) column - both FotMob's own"
        " per-player match figures (read from their per-player match stat groups, not derived from"
        " our shot map, since the shot map has no minutes/passer/assist fields to compute them from"
        " ourselves). Players with shots but no resolvable Minutes Played figure show blank; no"
        " resolvable xA figure shows 0.0. Any player with xA > 0 is included even if they took zero"
        " non-penalty shots themselves (their Shots/Goals/Total xG all show 0) - so a player who"
        " only created chances, without shooting, still shows up on this table.",
        "",
        "Plus Minus tab: one table per team, one row per player, with Minutes Played directly next"
        " to the player's name, then Goals For, Goals Against, Shots, Shots Against, xG, and xG"
        " Against - all totaled for exactly the minutes that player was on the pitch, not the"
        " match's grand total. A player's on-pitch window comes from FotMob's own lineup and"
        " substitution data (see extract_player_windows()): starts at 0 unless they came on as a"
        " substitute (start = their subIn minute), and ends at their subOut minute if they were"
        " substituted off, or otherwise at start + their own total Minutes Played figure (which"
        " already correctly accounts for stoppage time, and for a player sent off without being"
        " substituted, an early end to their minutes). A player who was subbed off does NOT get"
        " credit for the exact minute they left (that minute belongs to whoever replaced them);"
        " a player who finished the match DOES get credit for the final whistle minute itself, so"
        " a stoppage-time shot right at the end still counts for them. Bench players who never"
        " actually appeared aren't included - there's no on-pitch window to give them.",
        "",
        "FotMob's own per-player Minutes Played figure is sometimes missing or incomplete - most"
        " often for a very recently finished match FotMob hasn't fully processed yet - even when"
        " the shot map itself is already complete. When that happens for a player who otherwise"
        " clearly appeared (a lineup rating, or a sub event) and wasn't substituted off, their"
        " window falls back to an estimated match end (the latest minute seen anywhere on the shot"
        " map, or a flat 90 if there's no shot map either) rather than being left out - see"
        " extract_player_windows(). If FotMob returns NO lineup detail at all for this match (no"
        " starters/subs list, just a bare team name), this tab is empty entirely - there's no"
        " per-player data of any kind to build a window from in that case.",
        "",
        "Penalties are excluded from every one of the six Plus Minus columns, the same treatment as"
        " the Shot Breakdown tab. xG/xG Against are NOT a simple sum of each shot's own xG value -"
        " shots by the same team at the exact same effective minute (Minute + Added Time) are"
        " treated as one sequence (almost certainly a rebound/scramble in the same phase of play,"
        " since the shot map has no separate possession/sequence ID to group on more precisely)"
        " and combined into a single probability - 1 minus the product of (1 - xG) across that"
        " sequence's shots - rather than added together, since simply summing individual shot xG"
        " values would overstate the true combined chance of scoring from one spell of play. Shots"
        " in different minutes are treated as independent and their (already sequence-combined)"
        " values are simply added together as usual.",
        "",
        "xG Breakdown table (second table on the Totals tab): independent cuts of the same"
        " shot map - 1st Half Shots / 2nd Half Shots and 1st Half xG / 2nd Half xG (from FotMob's"
        " 'period' field; extra-time periods, if any, are lumped into 2nd Half rather than"
        " dropped), and Open Play xG / Set Piece xG (from FotMob's 'situation' field - Set Piece ="
        " SetPiece/FromCorner/Penalty situations, Open Play = everything else, e.g."
        " RegularPlay/FastBreak). These aren't mutually exclusive of each other - a set piece goal"
        " scored in the 2nd half adds to the 2nd Half Shots/xG columns as well as Set Piece xG.",
        "",
        "Unlike the WhoScored report, this data source does not provide a full",
        "event-by-event log (no per-touch/per-pass x/y data), so there is no Touches/Passing/",
        "Defensive Actions equivalent here - see this file's module docstring for why.",
        "",
        "If a run looks empty or wrong, check fotmob_raw_<matchId>.json (written next to this",
        "workbook) - FotMob's internal JSON schema isn't public and can drift; that raw file",
        "is the fastest way to see what actually came back and adjust the parsing.",
    ]
    for i, line in enumerate(notes, start=1):
        c = ws_notes.cell(row=i, column=1, value=line)
        c.font = Font(name='Arial', bold=(i == 1))
    ws_notes.column_dimensions['A'].width = 120

    return wb


# ============================================================
# 7. MAIN
# ============================================================
def sanitize_filename(name):
    return re.sub(r'[^A-Za-z0-9]+', '', name) if name else 'Unknown'


def main():
    parser = argparse.ArgumentParser(description='Generate a FotMob match shots/xG report.')
    parser.add_argument('url', help='FotMob match URL, e.g. https://www.fotmob.com/matches/<slug>/<code>#<matchId>')
    parser.add_argument('--out-dir', default='.', help='Directory to save the workbook + raw JSON debug dump in.')
    args = parser.parse_args()

    print(f"Scraping {args.url} ...")
    match_json, match_id = scrape_match(args.url, out_dir=args.out_dir)

    home_name, away_name = extract_team_names(match_json)
    print(f"Match {match_id}: {home_name} vs {away_name}")

    print("Computing shots...")
    shots_df = compute_shots(match_json)
    print(f"Found {len(shots_df)} shots.")
    if shots_df.empty:
        hint = extract_match_status_hint(match_json)
        if hint:
            print(f"No shots found - likely reason: {hint}")
        else:
            print("No shots found and no status hint available - check the raw JSON dump.")

    print("Computing totals...")
    totals_df = compute_totals(match_json, shots_df, home_name, away_name)

    print("Computing shot breakdowns...")
    player_xa = extract_player_xa(match_json)
    shot_breakdowns = compute_shot_breakdowns(shots_df, player_xa)

    print("Computing xG breakdown...")
    xg_breakdown = compute_xg_breakdown(shots_df, home_name, away_name)

    print("Building workbook...")
    wb = build_workbook(shots_df, totals_df, home_name, away_name, match_id, shot_breakdowns, xg_breakdown)

    filename = f"{sanitize_filename(home_name)}_vs_{sanitize_filename(away_name)}_fotmob.xlsx"
    out_path = os.path.join(args.out_dir, filename)
    wb.save(out_path)
    print(f"Saved: {out_path}")


if __name__ == '__main__':
    main()
